[package]
name = "iup"
version = "0.0.1"
authors = ["David Campbell <dcampbell24@gmail.com>"]

[lib]
name = "iup"
path = "src/iup/lib.rs"

[dependencies]
libc = "0.1"

[dependencies.iup-sys]
path = "iup-sys"
version = "*"
