[package]
name = "iup-sys"
description = "Raw IUP bindings for Rust used internally by iup-rust"
version = "0.0.1"
authors = ["David Campbell <dcampbell24@gmail.com>"]
build = "build.rs"
links = "IUP"

[lib]
name = "iup_sys"
path = "src/lib.rs"

[dependencies]
libc = "0.1"
